def translate(key, lang):
    if lang == 'uz':
        return uzb_lang[key]
    else:
        return rus_lang[key]


uzb_lang = {
    "welcome_text": "Salom! 👋 Карьерный Мастер qo'shilganingizdan juda xursandmiz, bu sizning professional yo'nalish va martaba qidirish bo'yicha yordamchingiz. Siz bu erda kasbga yo'naltirish bo'yicha so'rovnomada qatnashishingiz, shuningdek, onlayn kurslar va eng yaxshi universitetlar haqida ma'lumot olishingiz mumkin ✨ ✨ ",
    "prof_orientation": "🧑‍🎨Kasb yo'nalishi",
    "universities": "🧑‍🎓Universitetlar",
    "online_courses": "🌐Onlayn kurslar",
    "choose_option": "Variantlardan birini tanlang:",
    "take_test": "🧑‍💻Test sinovdan o'ting",
    "prof_info": "🌟Shaxsiylashtirilgan hisob-kitoblar, qimmatli manbalar va moslashtirilgan maslahatlar bilan oldindan yo'naltirish tizimi sizning professional yo'lingiz to'g'risida xabardor qarorlar qabul qilishga yordam beradi.💼 ✨",
    "comp_soft": "Dasturlash  bilan mosligi",
    "comp_design": "Dizaynga moslik",
    "comp_mark": "Marketingga moslik",
    "soft_courses": "Dasturlash kurslari",
    "design_courses": "Dizayn kurslari",
    "marketing_courses": "Marketing kurslari",
    "choose_course": "Kursni tanlang:",
    "jobs": "💻Ish",
    "unis_for_soft": "Dasturlash bo'yicha eng yaxshi universitetlar:\n\n",
    "unis_for_design": "Dizayn bo'yicha eng yaxshi universitetlar:\n\n",
    "unis_for_marketing": "Marketing bo'yicha eng yaxshi universitetlar:\n\n",
    "know_chances": "Qabul qilish imkoniyatlarini bilmoqchimisiz?",
    "choose_uni": "Universitetni tanlang:",
    "type_dtm_score": "DTM balini kiriting:",
    "type_ege_score": "ЕГЭ balini kiriting:",
    "your_chances": "Qabul qilinishingiz imkoniyati:",
    "your_chances_low": "Sizning imkoniyatingiz 30 dan kam%",
    "enter_numbers": "Faqat raqamlardan foydalaning",
    'name': 'Nomi',
    'acceptance': 'Qabul qilish foyizi',
    'graduation_rate': 'Yakunlash foyizi',
    'average_salary': 'Ortacha oylik',
    'link': 'Link',
}

rus_lang = {
    "welcome_text": "Привет! 👋 Мы очень рады, что вы присоединились к Pro Orientation, вашему помощнику в профессиональной ориентации и поиске карьеры. Вы здесь можете пройти опросник по профориентации, а также получить онлайн курсы и информцию о топовых университетах🌐 💼 ✨",
    "prof_orientation": "🧑‍🎨 Тест по профориентации",
    "universities": "🧑‍🎓 Университеты",
    "online_courses": "🌐 Онлайн курсы",
    "choose_option": "Выберите один из вариантов:",
    "take_test": "🧑‍💻Пройдите тест",
    "prof_info": "🌟Благодаря персонализированным оценкам, ценным ресурсам и индивидуальным советам система предварительной ориентации поможет вам принимать обоснованные решения относительно вашего профессионального пути.💼 ✨",
    "comp_soft": "Совместивость с Программированием",
    "comp_design": "Совместивость с Дизайном",
    "comp_mark": "Совместивость с Маркетингом",
    "soft_courses": "Курсы по программированию",
    "design_courses": "Курсы по дизайну",
    "marketing_courses": "Курсы по маркетингу",
    "choose_course": "Выберите курс:",
    "jobs": "💻Работы",
    "unis_for_soft": "Топ университетов по программированию:\n\n",
    "unis_for_design": "Топ университетов по дизайну:\n\n",
    "unis_for_marketing": "Топ университетов по маркетингу:\n\n",
    "know_chances": "Хотите узнать свои шансы поступления?",
    "choose_uni": "Выберите университет:",
    "type_dtm_score": "Введите балл ДТМ:",
    "type_ege_score": "Введите балл ЕГЭ:",
    "your_chances": "Ваш шанс поступить:",
    "your_chances_low": "Ваши шансы меньше 30%",
    "enter_numbers": "Используйте только числа",
    "name": "Название",
    "acceptance": "Процент зачисления",
    "graduation_rate": "Процент оканчивания",
    "average_salary": "Средняя зарплата",
    "link": "Ссылка",
}
